# Generated by Django 3.2.7 on 2021-09-24 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50, verbose_name='식자재명')),
                ('food_img', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('vegetables', '야채'), ('fruits', '과일'), ('meat', '육류'), ('fish', '수산'), ('etc', '기타')], default='etc', max_length=20, verbose_name='음식 카테고리')),
                ('description', models.TextField(verbose_name='상세정보')),
                ('quantity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='수량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('closed_at', models.DateTimeField(auto_now=True, verbose_name='마감시간')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='수량')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='주문시간')),
                ('pickup_at', models.DateTimeField(auto_now=True, verbose_name='픽업시간')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
