# Generated by Django 3.2.7 on 2021-09-25 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oauth',
            old_name='oauth_token',
            new_name='token',
        ),
        migrations.RenameField(
            model_name='oauth',
            old_name='oauth_type',
            new_name='type',
        ),
    ]
